CREATE TABLE [silver].[commissions] (

	[commission_id] varchar(50) NULL, 
	[type_operation] varchar(8000) NULL, 
	[operation_id] varchar(50) NULL, 
	[vente_id] varchar(50) NULL, 
	[souscription_id] varchar(50) NULL, 
	[operation_crowdfunding_id] varchar(50) NULL, 
	[investisseur_id] varchar(50) NULL, 
	[partenaire_id] varchar(50) NULL, 
	[conseiller_id] varchar(50) NULL, 
	[agence_id] varchar(50) NULL, 
	[produit_id] varchar(50) NULL, 
	[programme_id] varchar(50) NULL, 
	[montant_operation] decimal(18,2) NULL, 
	[taux_commission] decimal(9,4) NULL, 
	[montant_commission_brut] decimal(18,2) NULL, 
	[montant_commission_net] decimal(18,2) NULL, 
	[part_commission_partenaire] decimal(18,2) NULL, 
	[part_commission_interne] decimal(18,2) NULL, 
	[statut_commission] varchar(8000) NULL, 
	[date_calcul] date NULL, 
	[date_validation] date NULL, 
	[date_paiement] date NULL, 
	[mode_paiement] varchar(8000) NULL, 
	[motif_blocage] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL, 
	[is_deleted] bit NULL
);