CREATE TABLE [silver].[crm_prospects] (

	[prospect_id] varchar(50) NULL, 
	[civilite] varchar(8000) NULL, 
	[nom] varchar(8000) NULL, 
	[prenom] varchar(8000) NULL, 
	[email] varchar(8000) NULL, 
	[telephone] varchar(8000) NULL, 
	[date_naissance] date NULL, 
	[ville] varchar(8000) NULL, 
	[code_postal] varchar(8000) NULL, 
	[pays] varchar(8000) NULL, 
	[situation_familiale] varchar(8000) NULL, 
	[profession] varchar(8000) NULL, 
	[revenu_annuel_estime] decimal(18,2) NULL, 
	[patrimoine_estime] decimal(18,2) NULL, 
	[capacite_investissement] decimal(18,2) NULL, 
	[objectif_investissement] varchar(8000) NULL, 
	[horizon_investissement] varchar(8000) NULL, 
	[appetence_risque] varchar(8000) NULL, 
	[source_acquisition] varchar(8000) NULL, 
	[campagne_marketing] varchar(8000) NULL, 
	[canal_acquisition] varchar(8000) NULL, 
	[statut_prospect] varchar(8000) NULL, 
	[score_qualification] int NULL, 
	[date_creation] datetime2(6) NULL, 
	[created_by] varchar(8000) NULL, 
	[last_update_date] datetime2(6) NULL, 
	[last_updated_by] varchar(8000) NULL, 
	[is_deleted] bit NULL
);