CREATE TABLE [silver].[partenaires_patrimoine] (

	[partenaire_id] varchar(50) NULL, 
	[raison_sociale] varchar(8000) NULL, 
	[siret] varchar(8000) NULL, 
	[type_partenaire] varchar(8000) NULL, 
	[statut_partenaire] varchar(8000) NULL, 
	[nom_contact_principal] varchar(8000) NULL, 
	[prenom_contact_principal] varchar(8000) NULL, 
	[email_contact] varchar(8000) NULL, 
	[telephone_contact] varchar(8000) NULL, 
	[adresse] varchar(8000) NULL, 
	[ville] varchar(8000) NULL, 
	[code_postal] varchar(8000) NULL, 
	[region] varchar(8000) NULL, 
	[pays] varchar(8000) NULL, 
	[date_signature_convention] date NULL, 
	[niveau_partenaire] varchar(8000) NULL, 
	[segment_partenaire] varchar(8000) NULL, 
	[nombre_clients_actifs] int NULL, 
	[encours_total_apporte] decimal(18,2) NULL, 
	[commission_rate_default] decimal(9,4) NULL, 
	[manager_interne_id] varchar(50) NULL, 
	[conseiller_referent_id] varchar(50) NULL, 
	[statut_convention] varchar(8000) NULL, 
	[date_derniere_activite] date NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL, 
	[is_active] bit NULL
);