name: 'immo_fabric_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
test-paths: ["tests"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  lakehouse_name: "LH_Immo_Dev"

models:
  immo_fabric_dbt:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
    tech:
      +schema: tech
      +materialized: table