# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "66841f6d-142d-4f8a-98ff-9b81fed41000",
# META       "default_lakehouse_name": "LH_Immo_Dev",
# META       "default_lakehouse_workspace_id": "ec7aa1ee-16a6-43ef-a54d-cdcc1cb90693",
# META       "known_lakehouses": [
# META         {
# META           "id": "66841f6d-142d-4f8a-98ff-9b81fed41000"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# NB_01_Simulateur_Bronze — Génération J-1\n",
    "**Projet** : SI Immobilier Consultim  \n",
    "**Couche** : Bronze  \n",
    "**Mode** : Incrémental J-1 — APPEND uniquement  \n",
    "**Fabric** : Coller dans un Notebook Fabric, attacher au Lakehouse LH_Immobilier\n",
    "\n",
    "---\n",
    "### Comment utiliser ce notebook\n",
    "1. En exécution manuelle : laisser `DATE_EXECUTION = None` → prend automatiquement J-1\n",
    "2. En rejeu historique : passer une date ex. `DATE_EXECUTION = '2025-03-15'`\n",
    "3. Depuis un Pipeline Fabric : passer le paramètre `date_execution` via l'activité Notebook\n",
    "\n",
    "Toutes les variables de volume sont dans la cellule **[PARAMETRES]** ci-dessous."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ▶ CELLULE 1 — PARAMÈTRES\n",
    "**Modifier uniquement cette cellule pour ajuster les volumes.**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "tags": [
     "parameters"
    ]
   },
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# PARAMÈTRES GLOBAUX — Modifier ici pour changer les volumes\n",
    "# ============================================================\n",
    "\n",
    "# --- DATE D'EXÉCUTION ---\n",
    "# None = J-1 automatique | '2025-03-15' = rejeu d'une date spécifique\n",
    "DATE_EXECUTION = None\n",
    "\n",
    "# --- MODE ---\n",
    "# 'append'   : ajoute dans les tables Delta existantes (PROD normal)\n",
    "# 'overwrite': écrase (DEV uniquement)\n",
    "# 'dry_run'  : affiche sans écrire (test)\n",
    "MODE_ECRITURE = 'append'\n",
    "\n",
    "# --- NOM DU LAKEHOUSE ---\n",
    "# Changer selon l'environnement : LH_Immobilier_DEV / PREPROD / PROD\n",
    "LAKEHOUSE_NAME = 'LH_Immobilier_DEV'\n",
    "\n",
    "# ============================================================\n",
    "# VOLUMES PAR TABLE — lignes générées par jour\n",
    "# Format : (min, max) — le simulateur tire aléatoirement dans cet intervalle\n",
    "# Mettre (0, 0) pour désactiver une table\n",
    "# ============================================================\n",
    "\n",
    "VOL_PROSPECTS            = (3, 8)    # Nouveaux leads entrants / jour\n",
    "VOL_EVENEMENTS           = (10, 25)  # Interactions CRM / jour (appels, emails, RDV)\n",
    "VOL_RESERVATIONS         = (0, 3)    # Nouvelles réservations / jour\n",
    "VOL_VENTES               = (0, 2)    # Ventes signées / jour\n",
    "VOL_FINANCEMENTS         = (0, 2)    # Dossiers financement / jour\n",
    "VOL_DOSSIERS_ADV         = (1, 4)    # Mises à jour dossiers ADV / jour\n",
    "VOL_COMMISSIONS          = (0, 3)    # Commissions calculées / jour\n",
    "VOL_SOUSCRIPTIONS        = (0, 4)    # Souscriptions SCPI/SCI / jour\n",
    "VOL_CROWDFUNDING         = (0, 2)    # Opérations crowdfunding / jour\n",
    "VOL_GESTION_LOCATIVE     = (0, 2)    # Nouvelles gestions locatives / jour\n",
    "VOL_RECLAMATIONS         = (0, 2)    # Réclamations / jour\n",
    "VOL_REVENTAS             = (0, 1)    # Demandes de revente / jour\n",
    "VOL_LMNP                 = (0, 2)    # Dossiers comptables LMNP / jour\n",
    "\n",
    "# Tables générées en batch mensuel uniquement (1er du mois)\n",
    "VOL_OBJECTIFS_MENSUEL    = (30, 60)  # Objectifs commerciaux par mois\n",
    "\n",
    "# Tables référentielles — générées rarement (probabilité / jour)\n",
    "PROBA_NOUVEAU_PROGRAMME  = 0.05  # 5% de chance / jour d'avoir un nouveau programme\n",
    "PROBA_NOUVEAU_LOT        = 0.10  # 10% de chance / jour d'avoir de nouveaux lots\n",
    "PROBA_NOUVEAU_CONSEILLER = 0.02  # 2% de chance / jour (recrutement)\n",
    "PROBA_NOUVEAU_PARTENAIRE = 0.03  # 3% de chance / jour\n",
    "\n",
    "# ============================================================\n",
    "# RÉPARTITION PAR AGENCE — poids relatifs (doit sommer à 1.0)\n",
    "# ============================================================\n",
    "POIDS_AGENCES = {\n",
    "    'AG_0002': 0.20,  # Paris\n",
    "    'AG_0004': 0.15,  # Paris\n",
    "    'AG_0007': 0.15,  # Paris\n",
    "    'AG_0001': 0.12,  # Lille\n",
    "    'AG_0010': 0.10,  # Nantes\n",
    "    'AG_0005': 0.10,  # Montpellier\n",
    "    'AG_0006': 0.08,  # Grenoble\n",
    "    'AG_0009': 0.05,  # Strasbourg\n",
    "    'AG_0008': 0.03,  # Reims\n",
    "    'AG_0003': 0.02,  # Rouen\n",
    "}\n",
    "\n",
    "# ============================================================\n",
    "# SALETÉ BRONZE — probabilités d'erreurs par type\n",
    "# Mettre à 0.0 pour des données propres (Silver-like)\n",
    "# ============================================================\n",
    "TAUX_NULL_CHAMPS_OPTIONNELS  = 0.15   # 15% de nulls sur champs non obligatoires\n",
    "TAUX_FORMAT_TEL_INCORRECT    = 0.08   # 8% de téléphones mal formatés\n",
    "TAUX_STATUT_MAL_CASSE        = 0.06   # 6% de statuts avec casse incorrecte\n",
    "TAUX_DATE_INCOHERENTE        = 0.04   # 4% de dates légèrement incohérentes\n",
    "TAUX_DOUBLON_PROSPECT        = 0.03   # 3% de prospects en doublon\n",
    "TAUX_MONTANT_VIRGULE_POINT   = 0.05   # 5% de montants avec séparateur mixte\n",
    "\n",
    "# ============================================================\n",
    "# SEED ALÉATOIRE — pour reproductibilité en DEV\n",
    "# None = aléatoire réel (PROD) | entier = reproductible (DEV/tests)\n",
    "# ============================================================\n",
    "RANDOM_SEED = None"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ▶ CELLULE 2 — IMPORTS & INITIALISATION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "import string\n",
    "import warnings\n",
    "from datetime import datetime, timedelta, date\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pyspark.sql import SparkSession\n",
    "from pyspark.sql import functions as F\n",
    "from pyspark.sql.types import *\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Seed\n",
    "if RANDOM_SEED is not None:\n",
    "    random.seed(RANDOM_SEED)\n",
    "    np.random.seed(RANDOM_SEED)\n",
    "\n",
    "# Date J-1\n",
    "if DATE_EXECUTION is None:\n",
    "    DATE_J1 = datetime.today().date() - timedelta(days=1)\n",
    "else:\n",
    "    DATE_J1 = datetime.strptime(DATE_EXECUTION, '%Y-%m-%d').date()\n",
    "\n",
    "DATE_J1_STR = DATE_J1.strftime('%Y-%m-%d')\n",
    "IS_PREMIER_DU_MOIS = DATE_J1.day == 1\n",
    "IS_WEEKEND = DATE_J1.weekday() >= 5  # Samedi=5, Dimanche=6\n",
    "\n",
    "# Réduction activité le weekend\n",
    "FACTEUR_WEEKEND = 0.2 if IS_WEEKEND else 1.0\n",
    "\n",
    "print(f\"\"\"╔══════════════════════════════════════════════════════╗\n",
    "║  SIMULATEUR BRONZE — SI Immobilier Consultim         ║\n",
    "╠══════════════════════════════════════════════════════╣\n",
    "║  Date simulée  : {DATE_J1_STR}                        ║\n",
    "║  Mode écriture : {MODE_ECRITURE:<10}                       ║\n",
    "║  Lakehouse     : {LAKEHOUSE_NAME:<20}         ║\n",
    "║  Weekend       : {'OUI — activité réduite' if IS_WEEKEND else 'NON — activité normale'}              ║\n",
    "║  1er du mois   : {'OUI — objectifs générés' if IS_PREMIER_DU_MOIS else 'NON'}              ║\n",
    "╚══════════════════════════════════════════════════════╝\"\"\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ▶ CELLULE 3 — CHARGEMENT DES RÉFÉRENTIELS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Chargement des référentiels — lecture minimale (SELECT + FILTER)\n",
    "# On ne charge QUE les colonnes nécessaires\n",
    "# ============================================================\n",
    "\n",
    "def read_table(table_name, cols=None, filter_expr=None):\n",
    "    \"\"\"Lecture optimisée : colonnes et filtre poussés au niveau Delta.\"\"\"\n",
    "    df = spark.read.format('delta').table(f\"{LAKEHOUSE_NAME}.{table_name}\")\n",
    "    if filter_expr:\n",
    "        df = df.filter(filter_expr)\n",
    "    if cols:\n",
    "        df = df.select(cols)\n",
    "    return df.toPandas()\n",
    "\n",
    "def get_max_id(table_name, id_col, prefix, pad):\n",
    "    \"\"\"Récupère le dernier numéro d'ID pour incrémenter. Ne lit qu'une valeur.\"\"\"\n",
    "    result = spark.sql(f\"\"\"\n",
    "        SELECT MAX(CAST(REGEXP_REPLACE({id_col}, '[^0-9]', '') AS BIGINT)) as max_num\n",
    "        FROM {LAKEHOUSE_NAME}.{table_name}\n",
    "    \"\"\").collect()[0]['max_num']\n",
    "    return int(result) if result else 0\n",
    "\n",
    "def next_ids(prefix, start_num, count, pad=6):\n",
    "    \"\"\"Génère une liste d'IDs incrémentaux.\"\"\"\n",
    "    return [f\"{prefix}{str(start_num + i + 1).zfill(pad)}\" for i in range(count)]\n",
    "\n",
    "# --- Chargement référentiels (petites tables, lecture complète OK) ---\n",
    "print(\"Chargement des référentiels...\")\n",
    "\n",
    "REF_AGENCES = read_table(\n",
    "    'src_agences_regions',\n",
    "    cols=['agence_id', 'ville', 'region_id'],\n",
    "    filter_expr=\"is_active = true\"\n",
    ")\n",
    "\n",
    "REF_CONSEILLERS = read_table(\n",
    "    'src_conseillers',\n",
    "    cols=['conseiller_id', 'agence_id', 'region_id', 'specialite_produit'],\n",
    "    filter_expr=\"is_active = true\"\n",
    ")\n",
    "\n",
    "REF_PARTENAIRES = read_table(\n",
    "    'src_partenaires_patrimoine',\n",
    "    cols=['partenaire_id', 'agence_id' if 'agence_id' in [] else 'partenaire_id'],\n",
    "    filter_expr=\"is_active = true\"\n",
    ")\n",
    "# Correction : partenaires n'ont pas agence_id direct\n",
    "REF_PARTENAIRES = read_table(\n",
    "    'src_partenaires_patrimoine',\n",
    "    cols=['partenaire_id'],\n",
    "    filter_expr=\"is_active = true\"\n",
    ")\n",
    "\n",
    "REF_PROGRAMMES = read_table(\n",
    "    'src_programmes_immobiliers',\n",
    "    cols=['programme_id', 'statut_programme', 'dispositif_fiscal', 'ville'],\n",
    "    filter_expr=\"statut_programme IN ('Commercialisation', 'Travaux') AND is_active = true\"\n",
    ")\n",
    "\n",
    "REF_LOTS_DISPO = read_table(\n",
    "    'src_lots_immobiliers',\n",
    "    cols=['lot_id', 'programme_id', 'prix_final', 'loyer_estime_mensuel'],\n",
    "    filter_expr=\"statut_lot = 'Disponible' AND is_active = true\"\n",
    ")\n",
    "\n",
    "REF_INVESTISSEURS_ACTIFS = read_table(\n",
    "    'src_crm_investisseurs',\n",
    "    cols=['investisseur_id', 'conseiller_id', 'agence_id', 'profil_investisseur'],\n",
    "    filter_expr=\"statut_client = 'Actif' AND is_deleted = false\"\n",
    ")\n",
    "\n",
    "REF_PRODUITS = read_table(\n",
    "    'src_produits_investissement',\n",
    "    cols=['produit_id', 'famille_produit', 'type_produit', 'rendement_cible_annuel',\n",
    "          'montant_minimum_investissement', 'frais_entree'],\n",
    "    filter_expr=\"statut_commercialisation = 'Ouvert' AND is_active = true\"\n",
    ")\n",
    "\n",
    "REF_VENTES_ACTEES = read_table(\n",
    "    'src_ventes_immobilieres',\n",
    "    cols=['vente_id', 'investisseur_id', 'lot_id', 'programme_id',\n",
    "          'conseiller_id', 'agence_id', 'statut_vente'],\n",
    "    filter_expr=\"statut_vente IN ('Actee', 'Livree') AND is_deleted = false\"\n",
    ")\n",
    "\n",
    "# Listes utilitaires\n",
    "AGENCE_IDS   = list(REF_AGENCES['agence_id'])\n",
    "AGENCE_POIDS = [POIDS_AGENCES.get(a, 0.05) for a in AGENCE_IDS]\n",
    "PART_IDS     = list(REF_PARTENAIRES['partenaire_id'])\n",
    "PROD_IDS     = list(REF_PRODUITS['produit_id']) if len(REF_PRODUITS) > 0 else ['PROD_00001']\n",
    "\n",
    "print(f\"  ✓ {len(REF_AGENCES)} agences actives\")\n",
    "print(f\"  ✓ {len(REF_CONSEILLERS)} conseillers actifs\")\n",
    "print(f\"  ✓ {len(REF_PARTENAIRES)} partenaires actifs\")\n",
    "print(f\"  ✓ {len(REF_PROGRAMMES)} programmes en commercialisation\")\n",
    "print(f\"  ✓ {len(REF_LOTS_DISPO)} lots disponibles\")\n",
    "print(f\"  ✓ {len(REF_INVESTISSEURS_ACTIFS)} investisseurs actifs\")\n",
    "print(f\"  ✓ {len(REF_PRODUITS)} produits ouverts\")\n",
    "print(f\"  ✓ {len(REF_VENTES_ACTEES)} ventes actées/livrées (base gestion locative)\")\n",
    "print(\"Référentiels chargés ✓\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ▶ CELLULE 4 — FONCTIONS UTILITAIRES BRONZE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Utilitaires — saleté Bronze, choix pondérés, formats\n",
    "# ============================================================\n",
    "\n",
    "NOMS_FR = ['MARTIN','BERNARD','THOMAS','PETIT','ROBERT','RICHARD','DURAND',\n",
    "           'DUBOIS','MOREAU','SIMON','MICHEL','LEFEBVRE','LEROY','ROUX',\n",
    "           'DAVID','BERTRAND','MOREL','FOURNIER','GIRARD','BONNET','DUPONT',\n",
    "           'LAMBERT','FONTAINE','ROUSSEAU','VINCENT','MULLER','LEFEVRE',\n",
    "           'FAURE','ANDRE','MERCIER','BLANC','GUERIN','BOYER','GARNIER',\n",
    "           'CHEVALIER','FRANCOIS','LEGRAND','GAUTHIER','GARCIA','PERRIN',\n",
    "           'ROBIN','CLEMENT','MORIN','NICOLAS','HENRY','ROUSSEL','MATHIEU',\n",
    "           'GASSAMA','DIALLO','TRAORE','NDIAYE','FALL','BA','SOW','CAMARA',\n",
    "           'KONÉ','COULIBALY','DIARRA','TOURÉ','SANOGO','KEITA','BAMBA']\n",
    "\n",
    "PRENOMS_FR = ['Jean','Marie','Pierre','Sophie','Thomas','Julie','Nicolas',\n",
    "              'Camille','François','Laura','Antoine','Emma','Maxime','Léa',\n",
    "              'Alexandre','Manon','Julien','Chloé','Romain','Sarah','Lucas',\n",
    "              'Pauline','Quentin','Céline','Mathieu','Aurélie','Clément',\n",
    "              'Lucie','Baptiste','Amélie','Théo','Marion','Hugo','Anaïs',\n",
    "              'Alexis','Charlotte','Louis','Alice','Raphaël','Margot',\n",
    "              'Seydou','Fatou','Mamadou','Aissatou','Ousmane','Kadiatou']\n",
    "\n",
    "VILLES_FR = ['Paris','Lyon','Marseille','Toulouse','Nice','Nantes','Strasbourg',\n",
    "             'Montpellier','Bordeaux','Lille','Rennes','Reims','Le Havre',\n",
    "             'Saint-Étienne','Toulon','Grenoble','Dijon','Angers','Nîmes',\n",
    "             'Villeurbanne','Clermont-Ferrand','Le Mans','Aix-en-Provence',\n",
    "             'Brest','Tours','Amiens','Limoges','Metz','Perpignan','Caen']\n",
    "\n",
    "BANQUES = ['BNP Paribas','Société Générale','Crédit Agricole','LCL',\n",
    "           'Caisse d Epargne','Banque Populaire','Crédit Mutuel',\n",
    "           'CIC','HSBC France','ING Direct','Boursorama']\n",
    "\n",
    "COURTIERS = ['Courtier Partenaire A','CABINET FINANCEMENT PLUS',\n",
    "             'Financement Conseil','Meilleurtaux','Empruntis',\n",
    "             'Vousfinancer','Cafpi',None,None,None]  # Nulls = sans courtier\n",
    "\n",
    "SOURCES_ACQUISITION = ['LinkedIn','Evenement client','Partenaire','Referral',\n",
    "                        'Campagne emailing','Site web','Salon patrimoine','Google Ads']\n",
    "\n",
    "CAMPAGNES = ['Salon Patrimoine','Retargeting Google','Newsletter Q1','Newsletter Q2',\n",
    "             'Webinaire LMNP','Salon SCPI','Partenaire Premium',None,None]\n",
    "\n",
    "CANAUX = ['Email','Agence','Partenaire','Web']\n",
    "\n",
    "TYPES_EVENEMENT = ['Email','Point dossier','Webinaire','Rendez-vous','Relance','Appel']\n",
    "\n",
    "CANAUX_EVENEMENT = ['Agence','Visio','Telephone','Email']\n",
    "\n",
    "OBJETS_EVENEMENT = ['Qualification besoin','Point financement','Suivi dossier',\n",
    "                    'Presentation programme','Signature contrat','Relance prospect',\n",
    "                    'Bilan investissement','Point livraison']\n",
    "\n",
    "RESULTATS_EVENEMENT = ['Interesse','Dossier avance','En attente','Pas interesse',\n",
    "                       'A recontacter','Signature proche']\n",
    "\n",
    "PROCHAINES_ACTIONS = ['Demande pieces','Planifier rendez-vous','Envoyer documentation',\n",
    "                      'Relance sous 1 semaine','Proposer programme']\n",
    "\n",
    "DISPOSITIFS_FISCAUX = ['Pinel','LMNP','Nue-propriete','Denormandie','Pinel Plus',\n",
    "                       'LMNP micro-BIC','LMNP reel']\n",
    "\n",
    "MODES_PAIEMENT = ['Virement','Prelevement','Cheque']\n",
    "\n",
    "MOTIFS_RECLAMATION = [\n",
    "    'Demande de precision sur les frais',\n",
    "    'Client conteste les informations transmises',\n",
    "    'Delai de traitement trop long',\n",
    "    'Erreur sur le montant de commission',\n",
    "    'Document manquant dans le dossier',\n",
    "    'Probleme de communication conseiller'\n",
    "]\n",
    "\n",
    "TYPES_RECLAMATION = ['Delai traitement','Information incorrecte',\n",
    "                     'Erreur financiere','Qualite service']\n",
    "\n",
    "CATEGORIES_RECLAMATION = ['Conformite','Commercial','Technique','Administratif']\n",
    "\n",
    "NIVEAUX_URGENCE = ['Faible','Normal','Haute','Critique']\n",
    "NIVEAUX_URGENCE_POIDS = [0.4, 0.35, 0.18, 0.07]\n",
    "\n",
    "MOTIFS_REVENTE = ['Besoin liquidite','Fin horizon investissement',\n",
    "                  'Optimisation fiscale','Changement situation personnelle',\n",
    "                  'Opportunite reinvestissement']\n",
    "\n",
    "# ── Saleté Bronze ─────────────────────────────────────────\n",
    "\n",
    "def sale_telephone():\n",
    "    \"\"\"Génère un téléphone avec parfois un mauvais format (Bronze).\"\"\"\n",
    "    num = random.randint(600000000, 799999999)\n",
    "    if random.random() < TAUX_FORMAT_TEL_INCORRECT:\n",
    "        # Formats incorrects réalistes\n",
    "        formats = [\n",
    "            f\"+33{num}\",\n",
    "            f\"0033 {str(num)[:2]} {str(num)[2:4]} {str(num)[4:6]} {str(num)[6:8]} {str(num)[8:]}\",\n",
    "            f\"06-{str(num)[1:3]}-{str(num)[3:5]}-{str(num)[5:7]}-{str(num)[7:]}\",\n",
    "            str(num),  # Manque le 0 initial\n",
    "        ]\n",
    "        return random.choice(formats)\n",
    "    return str(num)\n",
    "\n",
    "def sale_statut(valeur_correcte, alternatives):\n",
    "    \"\"\"Introduit parfois une casse incorrecte sur un statut.\"\"\"\n",
    "    if random.random() < TAUX_STATUT_MAL_CASSE:\n",
    "        transformations = [\n",
    "            valeur_correcte.lower(),\n",
    "            valeur_correcte.upper(),\n",
    "            ' ' + valeur_correcte,  # Espace parasite\n",
    "        ]\n",
    "        return random.choice(transformations)\n",
    "    return valeur_correcte\n",
    "\n",
    "def sale_montant(montant):\n",
    "    \"\"\"Parfois retourne le montant comme string avec virgule (saisie manuelle).\"\"\"\n",
    "    if random.random() < TAUX_MONTANT_VIRGULE_POINT:\n",
    "        return str(montant).replace('.', ',')\n",
    "    return round(montant, 2)\n",
    "\n",
    "def sale_null(valeur, taux=None):\n",
    "    \"\"\"Introduit des nulls sur les champs optionnels.\"\"\"\n",
    "    t = taux if taux is not None else TAUX_NULL_CHAMPS_OPTIONNELS\n",
    "    return None if random.random() < t else valeur\n",
    "\n",
    "def sale_date(dt, direction='both'):\n",
    "    \"\"\"Introduit parfois une date légèrement incohérente.\"\"\"\n",
    "    if random.random() < TAUX_DATE_INCOHERENTE:\n",
    "        delta = random.randint(1, 15)\n",
    "        if direction == 'both':\n",
    "            delta = delta * random.choice([-1, 1])\n",
    "        return dt + timedelta(days=delta)\n",
    "    return dt\n",
    "\n",
    "# ── Helpers génériques ────────────────────────────────────\n",
    "\n",
    "def choix_agence():\n",
    "    \"\"\"Choisit une agence selon les poids définis.\"\"\"\n",
    "    return random.choices(AGENCE_IDS, weights=AGENCE_POIDS, k=1)[0]\n",
    "\n",
    "def conseiller_pour_agence(agence_id):\n",
    "    \"\"\"Retourne un conseiller actif de l'agence.\"\"\"\n",
    "    conseillers_agence = REF_CONSEILLERS[\n",
    "        REF_CONSEILLERS['agence_id'] == agence_id\n",
    "    ]['conseiller_id'].tolist()\n",
    "    if not conseillers_agence:\n",
    "        conseillers_agence = REF_CONSEILLERS['conseiller_id'].tolist()\n",
    "    return random.choice(conseillers_agence)\n",
    "\n",
    "def investisseur_pour_agence(agence_id):\n",
    "    \"\"\"Retourne un investisseur actif de l'agence.\"\"\"\n",
    "    inv_agence = REF_INVESTISSEURS_ACTIFS[\n",
    "        REF_INVESTISSEURS_ACTIFS['agence_id'] == agence_id\n",
    "    ]['investisseur_id'].tolist()\n",
    "    if not inv_agence:\n",
    "        inv_agence = REF_INVESTISSEURS_ACTIFS['investisseur_id'].tolist()\n",
    "    return random.choice(inv_agence) if inv_agence else None\n",
    "\n",
    "def lot_dispo_pour_programme(programme_id=None):\n",
    "    \"\"\"Retourne un lot disponible, filtré par programme si précisé.\"\"\"\n",
    "    if len(REF_LOTS_DISPO) == 0:\n",
    "        return None, None, None\n",
    "    if programme_id:\n",
    "        lots_prg = REF_LOTS_DISPO[\n",
    "            REF_LOTS_DISPO['programme_id'] == programme_id\n",
    "        ]\n",
    "        if len(lots_prg) > 0:\n",
    "            row = lots_prg.sample(1).iloc[0]\n",
    "            return row['lot_id'], row['programme_id'], row['prix_final']\n",
    "    row = REF_LOTS_DISPO.sample(1).iloc[0]\n",
    "    return row['lot_id'], row['programme_id'], row['prix_final']\n",
    "\n",
    "def email_fake(prenom, nom):\n",
    "    suffix = random.randint(100000, 999999)\n",
    "    domain = random.choice(['example-invest.fr','invest-conseil.fr',\n",
    "                            'patrimoine-plus.fr','gmail.com'])\n",
    "    p = prenom.lower().replace(' ','').replace('-','').replace(\"'\",'')\n",
    "    n = nom.lower().replace(' ','').replace('-','').replace(\"'\",'')\n",
    "    return f\"{p}.{n}{suffix}@{domain}\"\n",
    "\n",
    "def nb_lignes(vol_tuple):\n",
    "    \"\"\"Calcule le nombre de lignes à générer selon volume + facteur weekend.\"\"\"\n",
    "    mn, mx = vol_tuple\n",
    "    n = random.randint(mn, mx)\n",
    "    return max(0, int(n * FACTEUR_WEEKEND))\n",
    "\n",
    "def date_aleatoire_sur_j1():\n",
    "    \"\"\"Retourne un datetime sur la journée J-1.\"\"\"\n",
    "    h = random.randint(8, 19)\n",
    "    m = random.randint(0, 59)\n",
    "    return datetime.combine(DATE_J1, datetime.min.time()).replace(hour=h, minute=m)\n",
    "\n",
    "print(\"Utilitaires chargés ✓\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ▶ CELLULE 5 — GÉNÉRATEURS PAR TABLE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# GÉNÉRATEUR 1 — src_crm_prospects\n",
    "# ============================================================\n",
    "\n",
    "def generer_prospects(n, start_num):\n",
    "    rows = []\n",
    "    for i in range(n):\n",
    "        pid = f\"PROSP_{str(start_num + i + 1).zfill(6)}\"\n",
    "        nom = random.choice(NOMS_FR)\n",
    "        prenom = random.choice(PRENOMS_FR)\n",
    "        civ = random.choice(['Monsieur','Madame'])\n",
    "        ville = random.choice(VILLES_FR)\n",
    "        cp = str(random.randint(1000, 95999)).zfill(5)\n",
    "        revenu = random.randint(40000, 250000)\n",
    "        patrim = random.randint(50000, 2000000)\n",
    "        capacite = round(patrim * random.uniform(0.1, 0.4))\n",
    "        score = random.randint(10, 95)\n",
    "        source = random.choice(SOURCES_ACQUISITION)\n",
    "        campagne = sale_null(random.choice(CAMPAGNES))\n",
    "        canal = random.choice(CANAUX)\n",
    "        statut = sale_statut('Nouveau', ['nouveau','NOUVEAU',' Nouveau'])\n",
    "        created_by = random.choice(\n",
    "            ['crm_batch','conseiller','marketing_user'] +\n",
    "            REF_CONSEILLERS['conseiller_id'].tolist()[:5]\n",
    "        )\n",
    "\n",
    "        # Doublon potentiel Bronze\n",
    "        if random.random() < TAUX_DOUBLON_PROSPECT and i > 0:\n",
    "            prev = rows[-1].copy()\n",
    "            prev['prospect_id'] = pid\n",
    "            prev['created_at'] = DATE_J1_STR\n",
    "            rows.append(prev)\n",
    "            continue\n",
    "\n",
    "        naissance = date(\n",
    "            random.randint(1955, 1995),\n",
    "            random.randint(1, 12),\n",
    "            random.randint(1, 28)\n",
    "        ).strftime('%Y-%m-%d')\n",
    "\n",
    "        rows.append({\n",
    "            'prospect_id': pid,\n",
    "            'civilite': civ,\n",
    "            'nom': nom,\n",
    "            'prenom': prenom,\n",
    "            'email': email_fake(prenom, nom),\n",
    "            'telephone': sale_telephone(),\n",
    "            'date_naissance': naissance,\n",
    "            'ville': ville,\n",
    "            'code_postal': cp,\n",
    "            'pays': 'France',\n",
    "            'situation_familiale': random.choice(['Celibataire','Marie','Divorce','Pacs','Veuf']),\n",
    "            'profession': random.choice(['Cadre','Ingenieur','Medecin','Expert-comptable',\n",
    "                                          'Chef entreprise','Consultant','Fonctionnaire',\n",
    "                                          'Commercant','Avocat','Professeur']),\n",
    "            'revenu_annuel_estime': revenu,\n",
    "            'patrimoine_estime': patrim,\n",
    "            'capacite_investissement': capacite,\n",
    "            'objectif_investissement': random.choice(['Preparation retraite',\n",
    "                                                       'Diversification patrimoine',\n",
    "                                                       'Revenus complementaires',\n",
    "                                                       'Transmission patrimoine',\n",
    "                                                       'Defiscalisation']),\n",
    "            'horizon_investissement': random.choice(['Court terme','Moyen terme','Long terme']),\n",
    "            'appetence_risque': random.choice(['Faible','Moderee','Elevee']),\n",
    "            'source_acquisition': source,\n",
    "            'campagne_marketing': campagne,\n",
    "            'canal_acquisition': canal,\n",
    "            'statut_prospect': statut,\n",
    "            'score_qualification': score,\n",
    "            'date_creation': DATE_J1_STR,\n",
    "            'created_by': created_by,\n",
    "            'last_update_date': DATE_J1_STR,\n",
    "            'last_updated_by': created_by,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 2 — src_evenements_clients\n",
    "# ============================================================\n",
    "\n",
    "def generer_evenements(n, start_num):\n",
    "    rows = []\n",
    "    inv_ids = REF_INVESTISSEURS_ACTIFS['investisseur_id'].tolist()\n",
    "    for i in range(n):\n",
    "        eid = f\"EVT_{str(start_num + i + 1).zfill(7)}\"\n",
    "        agence_id = choix_agence()\n",
    "        conseiller_id = conseiller_pour_agence(agence_id)\n",
    "        investisseur_id = sale_null(investisseur_pour_agence(agence_id), taux=0.1)\n",
    "        prospect_id = sale_null(f\"PROSP_{str(random.randint(1, 1000)).zfill(6)}\", taux=0.3)\n",
    "        partenaire_id = sale_null(random.choice(PART_IDS), taux=0.6)\n",
    "        type_evt = random.choice(TYPES_EVENEMENT)\n",
    "        date_evt = date_aleatoire_sur_j1()\n",
    "        statut = sale_statut('Realise', ['realise','REALISE'])\n",
    "        date_prochaine = sale_null(\n",
    "            (DATE_J1 + timedelta(days=random.randint(3, 21))).strftime('%Y-%m-%d')\n",
    "        )\n",
    "        rows.append({\n",
    "            'evenement_id': eid,\n",
    "            'investisseur_id': investisseur_id,\n",
    "            'prospect_id': prospect_id,\n",
    "            'partenaire_id': partenaire_id,\n",
    "            'conseiller_id': conseiller_id,\n",
    "            'type_evenement': type_evt,\n",
    "            'canal_evenement': random.choice(CANAUX_EVENEMENT),\n",
    "            'objet_evenement': random.choice(OBJETS_EVENEMENT),\n",
    "            'date_evenement': date_evt.strftime('%Y-%m-%d'),\n",
    "            'statut_evenement': statut,\n",
    "            'resultat_evenement': sale_null(random.choice(RESULTATS_EVENEMENT), taux=0.2),\n",
    "            'prochaine_action': sale_null(random.choice(PROCHAINES_ACTIONS)),\n",
    "            'date_prochaine_action': date_prochaine,\n",
    "            'priorite': random.choice(['Faible','Normale','Haute','Critique']),\n",
    "            'commentaire': sale_null(random.choice([\n",
    "                'Echange complet avec le client',\n",
    "                'Client interesse, relance prevue',\n",
    "                'Attente retour client',\n",
    "                'Dossier en cours de constitution',\n",
    "                'Client relance',\n",
    "                'Point fait, bon avancement'\n",
    "            ])),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'created_by': conseiller_id,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 3 — src_reservations_immobilieres\n",
    "# ============================================================\n",
    "\n",
    "def generer_reservations(n, start_num):\n",
    "    rows = []\n",
    "    if len(REF_LOTS_DISPO) == 0:\n",
    "        print(\"  ⚠ Aucun lot disponible — réservations ignorées\")\n",
    "        return pd.DataFrame()\n",
    "    for i in range(n):\n",
    "        rid = f\"RES_{str(start_num + i + 1).zfill(6)}\"\n",
    "        agence_id = choix_agence()\n",
    "        conseiller_id = conseiller_pour_agence(agence_id)\n",
    "        investisseur_id = investisseur_pour_agence(agence_id)\n",
    "        if investisseur_id is None:\n",
    "            continue\n",
    "        lot_id, programme_id, prix = lot_dispo_pour_programme()\n",
    "        if lot_id is None:\n",
    "            continue\n",
    "        remise = round(random.uniform(0, prix * 0.03), 2)\n",
    "        prix_reserve = round(prix - remise, 2)\n",
    "        apport = round(prix_reserve * random.uniform(0.05, 0.30), 2)\n",
    "        credit = round(prix_reserve - apport, 2)\n",
    "        date_exp = (DATE_J1 + timedelta(days=random.randint(30, 60))).strftime('%Y-%m-%d')\n",
    "        mode_fin = random.choice(['Mixte','Credit','Comptant','Mixte','Mixte'])\n",
    "        rows.append({\n",
    "            'reservation_id': rid,\n",
    "            'lot_id': lot_id,\n",
    "            'programme_id': programme_id,\n",
    "            'investisseur_id': investisseur_id,\n",
    "            'partenaire_id': sale_null(random.choice(PART_IDS)),\n",
    "            'conseiller_id': conseiller_id,\n",
    "            'agence_id': agence_id,\n",
    "            'date_reservation': DATE_J1_STR,\n",
    "            'montant_reservation': random.choice([2000, 3000, 4000, 5000]),\n",
    "            'prix_reserve': prix_reserve,\n",
    "            'remise_appliquee': remise,\n",
    "            'statut_reservation': sale_statut('Active', ['active','ACTIVE']),\n",
    "            'motif_annulation': None,\n",
    "            'date_annulation': None,\n",
    "            'date_expiration_reservation': date_exp,\n",
    "            'canal_reservation': random.choice(['Web','Agence','Partenaire','Telephone']),\n",
    "            'mode_financement_prevu': mode_fin,\n",
    "            'apport_prevu': apport if mode_fin != 'Comptant' else prix_reserve,\n",
    "            'montant_credit_prevu': credit if mode_fin != 'Comptant' else 0,\n",
    "            'commentaire_commercial': sale_null(random.choice([\n",
    "                'Dossier prioritaire','Profil solide','Client VIP',\n",
    "                'Financement en cours','Apport confortable',None\n",
    "            ])),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 4 — src_ventes_immobilieres\n",
    "# ============================================================\n",
    "\n",
    "def generer_ventes(n, start_num, reservations_du_jour):\n",
    "    rows = []\n",
    "    # Les ventes du jour correspondent à des réservations antérieures transformées\n",
    "    res_ids_existants = spark.sql(\n",
    "        f\"\"\"SELECT reservation_id, lot_id, programme_id, investisseur_id,\n",
    "               partenaire_id, conseiller_id, agence_id, prix_reserve, apport_prevu\n",
    "            FROM {LAKEHOUSE_NAME}.src_reservations_immobilieres\n",
    "            WHERE statut_reservation = 'Active'\n",
    "            AND is_deleted = false\n",
    "            ORDER BY RAND() LIMIT {n * 3}\"\"\"\n",
    "    ).toPandas()\n",
    "\n",
    "    if len(res_ids_existants) == 0:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    sample = res_ids_existants.sample(min(n, len(res_ids_existants)))\n",
    "\n",
    "    for i, (_, res) in enumerate(sample.iterrows()):\n",
    "        vid = f\"VTE_{str(start_num + i + 1).zfill(6)}\"\n",
    "        prix_ht = round(float(res['prix_reserve']) / 1.20, 2)\n",
    "        tva = round(float(res['prix_reserve']) - prix_ht, 2)\n",
    "        frais_notaire = round(float(res['prix_reserve']) * random.uniform(0.025, 0.04), 2)\n",
    "        montant_total = round(float(res['prix_reserve']) + frais_notaire, 2)\n",
    "        apport = float(res['apport_prevu']) if res['apport_prevu'] else round(float(res['prix_reserve']) * 0.15, 2)\n",
    "        credit = round(float(res['prix_reserve']) - apport, 2)\n",
    "        mode_fin = 'Credit' if credit > 0 else 'Comptant'\n",
    "        date_acte = sale_date(DATE_J1 + timedelta(days=random.randint(45, 120)))\n",
    "        date_livraison = sale_date(DATE_J1 + timedelta(days=random.randint(300, 700)))\n",
    "\n",
    "        rows.append({\n",
    "            'vente_id': vid,\n",
    "            'reservation_id': res['reservation_id'],\n",
    "            'lot_id': res['lot_id'],\n",
    "            'programme_id': res['programme_id'],\n",
    "            'investisseur_id': res['investisseur_id'],\n",
    "            'partenaire_id': res['partenaire_id'],\n",
    "            'conseiller_id': res['conseiller_id'],\n",
    "            'agence_id': res['agence_id'],\n",
    "            'date_signature_contrat': DATE_J1_STR,\n",
    "            'date_signature_acte': date_acte.strftime('%Y-%m-%d'),\n",
    "            'date_livraison_prevue': date_livraison.strftime('%Y-%m-%d'),\n",
    "            'date_livraison_reelle': None,\n",
    "            'prix_vente_ht': prix_ht,\n",
    "            'prix_vente_ttc': float(res['prix_reserve']),\n",
    "            'tva': tva,\n",
    "            'frais_notaire': frais_notaire,\n",
    "            'montant_total_operation': montant_total,\n",
    "            'mode_financement': mode_fin,\n",
    "            'montant_apport': apport,\n",
    "            'montant_credit': credit,\n",
    "            'banque_financement': sale_null(random.choice(BANQUES), taux=0.3),\n",
    "            'statut_vente': sale_statut('Signee', ['signee','SIGNEE']),\n",
    "            'motif_echec': None,\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 5 — src_financements\n",
    "# ============================================================\n",
    "\n",
    "def generer_financements(n, start_num):\n",
    "    rows = []\n",
    "    ventes_recentes = spark.sql(\n",
    "        f\"\"\"SELECT vente_id, investisseur_id, prix_vente_ttc, montant_apport, montant_credit\n",
    "            FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres\n",
    "            WHERE statut_vente = 'Signee' AND montant_credit > 0\n",
    "            AND is_deleted = false\n",
    "            ORDER BY RAND() LIMIT {n * 3}\"\"\"\n",
    "    ).toPandas()\n",
    "\n",
    "    if len(ventes_recentes) == 0:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    sample = ventes_recentes.sample(min(n, len(ventes_recentes)))\n",
    "\n",
    "    for i, (_, v) in enumerate(sample.iterrows()):\n",
    "        fid = f\"FIN_{str(start_num + i + 1).zfill(6)}\"\n",
    "        montant_credit = float(v['montant_credit'])\n",
    "        apport = float(v['montant_apport'])\n",
    "        taux = round(random.uniform(0.025, 0.048), 4)\n",
    "        duree = random.choice([180, 240, 300])\n",
    "        mensualite = round(\n",
    "            montant_credit * (taux / 12) / (1 - (1 + taux / 12) ** (-duree)), 2\n",
    "        )\n",
    "        accord_principe = sale_date(DATE_J1 + timedelta(days=random.randint(10, 25)))\n",
    "        offre_pret = sale_date(accord_principe + timedelta(days=random.randint(15, 30)))\n",
    "        statut = sale_statut(\n",
    "            random.choice(['Demande deposee','Accord principe','Offre emise']),\n",
    "            []\n",
    "        )\n",
    "        rows.append({\n",
    "            'financement_id': fid,\n",
    "            'vente_id': v['vente_id'],\n",
    "            'investisseur_id': v['investisseur_id'],\n",
    "            'banque': random.choice(BANQUES),\n",
    "            'courtier': sale_null(random.choice(COURTIERS)),\n",
    "            'montant_demande': sale_montant(montant_credit + apport * 0.05),\n",
    "            'montant_accorde': sale_null(sale_montant(montant_credit), taux=0.3),\n",
    "            'taux_credit': taux,\n",
    "            'duree_credit_mois': duree,\n",
    "            'mensualite_estimee': mensualite,\n",
    "            'statut_financement': statut,\n",
    "            'date_demande': DATE_J1_STR,\n",
    "            'date_accord_principe': accord_principe.strftime('%Y-%m-%d'),\n",
    "            'date_offre_pret': sale_null(offre_pret.strftime('%Y-%m-%d'), taux=0.4),\n",
    "            'date_acceptation_offre': None,\n",
    "            'motif_refus': None,\n",
    "            'apport_personnel': apport,\n",
    "            'assurance_emprunteur': round(montant_credit * random.uniform(0.001, 0.004), 2),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 6 — src_commissions\n",
    "# ============================================================\n",
    "\n",
    "def generer_commissions(n, start_num):\n",
    "    rows = []\n",
    "    ventes_pour_comm = spark.sql(\n",
    "        f\"\"\"SELECT vente_id, investisseur_id, partenaire_id, conseiller_id,\n",
    "               agence_id, programme_id, prix_vente_ttc\n",
    "            FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres\n",
    "            WHERE is_deleted = false\n",
    "            ORDER BY RAND() LIMIT {n * 2}\"\"\"\n",
    "    ).toPandas()\n",
    "\n",
    "    for i in range(min(n, len(ventes_pour_comm))):\n",
    "        cid = f\"COM_{str(start_num + i + 1).zfill(6)}\"\n",
    "        v = ventes_pour_comm.iloc[i]\n",
    "        type_op = random.choices(\n",
    "            ['vente','souscription','crowdfunding'],\n",
    "            weights=[0.56, 0.30, 0.14]\n",
    "        )[0]\n",
    "        montant_op = float(v['prix_vente_ttc'])\n",
    "        taux = round(random.uniform(0.025, 0.055), 4)\n",
    "        comm_brut = round(montant_op * taux, 2)\n",
    "        comm_net = round(comm_brut * random.uniform(0.88, 0.96), 2)\n",
    "        part_part = round(comm_brut * random.uniform(0, 0.25), 2) if v['partenaire_id'] else 0.0\n",
    "        part_int = round(comm_brut - part_part, 2)\n",
    "        statut = random.choices(\n",
    "            ['Calculee','En validation','Validee','Payee','Bloquee'],\n",
    "            weights=[0.30, 0.20, 0.25, 0.20, 0.05]\n",
    "        )[0]\n",
    "        date_valid = sale_null(\n",
    "            (DATE_J1 + timedelta(days=random.randint(3, 15))).strftime('%Y-%m-%d'),\n",
    "            taux=0.4\n",
    "        )\n",
    "        rows.append({\n",
    "            'commission_id': cid,\n",
    "            'type_operation': type_op,\n",
    "            'operation_id': v['vente_id'],\n",
    "            'vente_id': v['vente_id'] if type_op == 'vente' else None,\n",
    "            'souscription_id': None,\n",
    "            'operation_crowdfunding_id': None,\n",
    "            'investisseur_id': v['investisseur_id'],\n",
    "            'partenaire_id': v['partenaire_id'],\n",
    "            'conseiller_id': v['conseiller_id'],\n",
    "            'agence_id': v['agence_id'],\n",
    "            'produit_id': None,\n",
    "            'programme_id': v['programme_id'],\n",
    "            'montant_operation': sale_montant(montant_op),\n",
    "            'taux_commission': taux,\n",
    "            'montant_commission_brut': comm_brut,\n",
    "            'montant_commission_net': comm_net,\n",
    "            'part_commission_partenaire': part_part,\n",
    "            'part_commission_interne': part_int,\n",
    "            'statut_commission': sale_statut(statut, [statut.lower(), statut.upper()]),\n",
    "            'date_calcul': DATE_J1_STR,\n",
    "            'date_validation': date_valid,\n",
    "            'date_paiement': None,\n",
    "            'mode_paiement': sale_null('Virement'),\n",
    "            'motif_blocage': None,\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 7 — src_dossiers_adv\n",
    "# ============================================================\n",
    "\n",
    "def generer_dossiers_adv(n, start_num):\n",
    "    rows = []\n",
    "    ventes_base = spark.sql(\n",
    "        f\"\"\"SELECT vente_id, reservation_id, investisseur_id, lot_id,\n",
    "               programme_id, partenaire_id, conseiller_id\n",
    "            FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres\n",
    "            WHERE statut_vente IN ('Signee','Actee')\n",
    "            AND is_deleted = false\n",
    "            ORDER BY RAND() LIMIT {n * 3}\"\"\"\n",
    "    ).toPandas()\n",
    "\n",
    "    if len(ventes_base) == 0:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    adv_ids = [f\"ADVRESP_{str(random.randint(1,25)).zfill(3)}\" for _ in range(25)]\n",
    "    pieces_possibles = ['Mandat signe','CNI','Bulletins salaire','Avis imposition',\n",
    "                         'RIB','Justificatif domicile',None]\n",
    "    statuts_adv = ['Ouvert','Pieces en attente','En validation',\n",
    "                   'Envoye notaire','Signe','Cloture']\n",
    "\n",
    "    sample = ventes_base.sample(min(n, len(ventes_base)))\n",
    "    for i, (_, v) in enumerate(sample.iterrows()):\n",
    "        did = f\"ADV_{str(start_num + i + 1).zfill(6)}\"\n",
    "        statut = random.choice(statuts_adv)\n",
    "        date_recep = sale_null(\n",
    "            (DATE_J1 + timedelta(days=random.randint(1, 10))).strftime('%Y-%m-%d'),\n",
    "            taux=0.2\n",
    "        )\n",
    "        date_valid = sale_null(\n",
    "            (DATE_J1 + timedelta(days=random.randint(5, 20))).strftime('%Y-%m-%d'),\n",
    "            taux=0.35\n",
    "        )\n",
    "        rows.append({\n",
    "            'dossier_adv_id': did,\n",
    "            'vente_id': v['vente_id'],\n",
    "            'reservation_id': v['reservation_id'],\n",
    "            'investisseur_id': v['investisseur_id'],\n",
    "            'lot_id': sale_null(v['lot_id'], taux=0.1),\n",
    "            'programme_id': v['programme_id'],\n",
    "            'partenaire_id': v['partenaire_id'],\n",
    "            'conseiller_id': v['conseiller_id'],\n",
    "            'statut_dossier': sale_statut(statut, [statut.lower()]),\n",
    "            'date_ouverture_dossier': DATE_J1_STR,\n",
    "            'date_reception_pieces': date_recep,\n",
    "            'date_validation_dossier': date_valid,\n",
    "            'date_envoi_notaire': None,\n",
    "            'date_signature_acte': None,\n",
    "            'delai_traitement_jours': random.randint(5, 45),\n",
    "            'pieces_manquantes': sale_null(random.choice(pieces_possibles)),\n",
    "            'nombre_relances': random.randint(0, 8),\n",
    "            'blocage_adv': random.random() < 0.1,\n",
    "            'motif_blocage': None,\n",
    "            'responsable_adv_id': random.choice(adv_ids),\n",
    "            'commentaire_adv': sale_null(random.choice([\n",
    "                'Client relance','Controle complementaire requis',\n",
    "                'En attente notaire','Dossier complet','Validation en cours'\n",
    "            ])),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 8 — src_souscriptions_pierre_papier\n",
    "# ============================================================\n",
    "\n",
    "def generer_souscriptions(n, start_num):\n",
    "    rows = []\n",
    "    soc_gest = [f\"SG_{str(i).zfill(3)}\" for i in range(1, 10)]\n",
    "    types_support = ['SCPI','SCI','OPCI']\n",
    "    noms_supports = [\n",
    "        'SCPI Horizon','SCI Patrimoine','SCPI Rendement',\n",
    "        'OPCI Diversifie','SCI Premium','SCPI Bureaux'\n",
    "    ]\n",
    "\n",
    "    for i in range(n):\n",
    "        sid = f\"SOU_{str(start_num + i + 1).zfill(6)}\"\n",
    "        agence_id = choix_agence()\n",
    "        conseiller_id = conseiller_pour_agence(agence_id)\n",
    "        investisseur_id = investisseur_pour_agence(agence_id)\n",
    "        if investisseur_id is None:\n",
    "            continue\n",
    "        produit_id = random.choice(PROD_IDS)\n",
    "        prix_part = random.choice([100, 200, 500, 1000])\n",
    "        nb_parts = random.randint(5, 500)\n",
    "        montant = prix_part * nb_parts\n",
    "        frais = round(montant * random.uniform(0.04, 0.10), 1)\n",
    "        rendement = round(random.uniform(0.04, 0.09), 4)\n",
    "        type_support = random.choice(types_support)\n",
    "        statut = random.choices(\n",
    "            ['En cours','Validee','Rejetee'],\n",
    "            weights=[0.20, 0.70, 0.10]\n",
    "        )[0]\n",
    "        date_valid = sale_null(\n",
    "            (DATE_J1 + timedelta(days=random.randint(5, 20))).strftime('%Y-%m-%d'),\n",
    "            taux=0.2\n",
    "        )\n",
    "        rows.append({\n",
    "            'souscription_id': sid,\n",
    "            'investisseur_id': investisseur_id,\n",
    "            'partenaire_id': sale_null(random.choice(PART_IDS)),\n",
    "            'conseiller_id': conseiller_id,\n",
    "            'agence_id': agence_id,\n",
    "            'produit_id': produit_id,\n",
    "            'societe_gestion_id': random.choice(soc_gest),\n",
    "            'type_support': type_support,\n",
    "            'nom_support': f\"{random.choice(noms_supports)} {random.randint(1,15)}\",\n",
    "            'date_souscription': DATE_J1_STR,\n",
    "            'montant_souscrit': montant,\n",
    "            'nombre_parts': nb_parts,\n",
    "            'prix_part': prix_part,\n",
    "            'frais_souscription': frais,\n",
    "            'duree_recommandee': random.choice([36, 60, 84, 120]),\n",
    "            'rendement_previsionnel': rendement,\n",
    "            'statut_souscription': sale_statut(statut, [statut.lower()]),\n",
    "            'date_validation': date_valid,\n",
    "            'date_rejet': None,\n",
    "            'motif_rejet': None,\n",
    "            'mode_paiement': random.choice(MODES_PAIEMENT),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 9 — src_gestion_locative\n",
    "# ============================================================\n",
    "\n",
    "def generer_gestion_locative(n, start_num):\n",
    "    rows = []\n",
    "    if len(REF_VENTES_ACTEES) == 0:\n",
    "        return pd.DataFrame()\n",
    "    gest_ids = [f\"GEST_{str(i).zfill(3)}\" for i in range(1, 40)]\n",
    "    sample = REF_VENTES_ACTEES.sample(min(n, len(REF_VENTES_ACTEES)))\n",
    "\n",
    "    for i, (_, v) in enumerate(sample.iterrows()):\n",
    "        gid = f\"GL_{str(start_num + i + 1).zfill(6)}\"\n",
    "        loyer_prevu = round(random.uniform(600, 3500), 2)\n",
    "        taux_occ = round(random.uniform(0.70, 0.99), 4)\n",
    "        loyer_reel = round(loyer_prevu * taux_occ, 2)\n",
    "        vacance = random.randint(0, 90) if taux_occ < 0.90 else random.randint(0, 15)\n",
    "        incident = random.random() < 0.08\n",
    "        impayes = round(loyer_reel * random.uniform(0.5, 2), 2) if incident else 0.0\n",
    "        rendement = round((loyer_reel * 12) / random.uniform(150000, 600000), 4)\n",
    "        rows.append({\n",
    "            'gestion_id': gid,\n",
    "            'vente_id': v['vente_id'],\n",
    "            'lot_id': sale_null(v['lot_id'], taux=0.15),\n",
    "            'investisseur_id': sale_null(v['investisseur_id'], taux=0.1),\n",
    "            'programme_id': v['programme_id'],\n",
    "            'gestionnaire_id': random.choice(gest_ids),\n",
    "            'date_debut_gestion': DATE_J1_STR,\n",
    "            'date_fin_gestion': None,\n",
    "            'statut_gestion': 'Active',\n",
    "            'loyer_mensuel_prevu': loyer_prevu,\n",
    "            'loyer_mensuel_reel': loyer_reel,\n",
    "            'taux_occupation': taux_occ,\n",
    "            'vacance_locative_jours': vacance,\n",
    "            'charges_mensuelles': round(loyer_prevu * random.uniform(0.15, 0.25), 2),\n",
    "            'incident_locatif': incident,\n",
    "            'montant_impayes': impayes,\n",
    "            'rendement_reel_annuel': rendement,\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_active': True\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 10 — src_reclamations_incidents\n",
    "# ============================================================\n",
    "\n",
    "def generer_reclamations(n, start_num):\n",
    "    rows = []\n",
    "    inv_ids = REF_INVESTISSEURS_ACTIFS['investisseur_id'].tolist()\n",
    "    ops = spark.sql(\n",
    "        f\"\"\"SELECT vente_id as operation_id, 'vente' as type_op\n",
    "            FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres\n",
    "            WHERE is_deleted = false\n",
    "            ORDER BY RAND() LIMIT {n * 3}\"\"\"\n",
    "    ).toPandas()\n",
    "\n",
    "    resp_ids = [f\"RESPREC_{str(i).zfill(3)}\" for i in range(1, 25)]\n",
    "    for i in range(n):\n",
    "        rid = f\"REC_{str(start_num + i + 1).zfill(6)}\"\n",
    "        op = ops.iloc[i % len(ops)] if len(ops) > 0 else None\n",
    "        urgence = random.choices(\n",
    "            NIVEAUX_URGENCE,\n",
    "            weights=NIVEAUX_URGENCE_POIDS\n",
    "        )[0]\n",
    "        statut = random.choices(\n",
    "            ['Ouverte','En cours','En attente','Cloturee'],\n",
    "            weights=[0.30, 0.30, 0.15, 0.25]\n",
    "        )[0]\n",
    "        date_resol = sale_null(\n",
    "            (DATE_J1 + timedelta(days=random.randint(2, 30))).strftime('%Y-%m-%d'),\n",
    "            taux=0.5\n",
    "        )\n",
    "        rows.append({\n",
    "            'reclamation_id': rid,\n",
    "            'investisseur_id': random.choice(inv_ids) if inv_ids else None,\n",
    "            'partenaire_id': sale_null(random.choice(PART_IDS)),\n",
    "            'operation_id': op['operation_id'] if op is not None else None,\n",
    "            'type_operation': op['type_op'] if op is not None else 'vente',\n",
    "            'type_reclamation': random.choice(TYPES_RECLAMATION),\n",
    "            'categorie_reclamation': random.choice(CATEGORIES_RECLAMATION),\n",
    "            'niveau_urgence': urgence,\n",
    "            'statut_reclamation': sale_statut(statut, [statut.lower()]),\n",
    "            'date_ouverture': DATE_J1_STR,\n",
    "            'date_resolution': date_resol,\n",
    "            'delai_resolution_jours': sale_null(random.randint(1, 45)),\n",
    "            'responsable_traitement_id': random.choice(resp_ids),\n",
    "            'motif_reclamation': random.choice(MOTIFS_RECLAMATION),\n",
    "            'resolution_apportee': sale_null(random.choice([\n",
    "                'Geste commercial propose','Correction effectuee',\n",
    "                'Information transmise','Dossier rouvert',None\n",
    "            ])),\n",
    "            'impact_financier_estime': sale_null(round(random.uniform(0, 5000), 2)),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 11 — src_revente_biens\n",
    "# ============================================================\n",
    "\n",
    "def generer_reventas(n, start_num):\n",
    "    rows = []\n",
    "    ventes_livrees = spark.sql(\n",
    "        f\"\"\"SELECT vente_id, lot_id, investisseur_id, programme_id, prix_vente_ttc\n",
    "            FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres\n",
    "            WHERE statut_vente = 'Livree'\n",
    "            AND is_deleted = false\n",
    "            ORDER BY RAND() LIMIT {n * 3}\"\"\"\n",
    "    ).toPandas()\n",
    "\n",
    "    if len(ventes_livrees) == 0:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    sample = ventes_livrees.sample(min(n, len(ventes_livrees)))\n",
    "    cons_ids = REF_CONSEILLERS['conseiller_id'].tolist()\n",
    "\n",
    "    for i, (_, v) in enumerate(sample.iterrows()):\n",
    "        rid = f\"REV_{str(start_num + i + 1).zfill(6)}\"\n",
    "        prix_achat = float(v['prix_vente_ttc'])\n",
    "        plus_value_rate = random.uniform(0.05, 0.30)\n",
    "        prix_estime = round(prix_achat * (1 + plus_value_rate), 2)\n",
    "        date_marche = (DATE_J1 + timedelta(days=random.randint(5, 15))).strftime('%Y-%m-%d')\n",
    "        rows.append({\n",
    "            'revente_id': rid,\n",
    "            'vente_id': v['vente_id'],\n",
    "            'lot_id': v['lot_id'],\n",
    "            'investisseur_id': v['investisseur_id'],\n",
    "            'programme_id': v['programme_id'],\n",
    "            'date_demande_revente': DATE_J1_STR,\n",
    "            'date_mise_en_marche': date_marche,\n",
    "            'date_revente': None,\n",
    "            'prix_achat_initial': prix_achat,\n",
    "            'prix_revente_estime': prix_estime,\n",
    "            'prix_revente_final': None,\n",
    "            'plus_value_brute': None,\n",
    "            'plus_value_nette': None,\n",
    "            'statut_revente': sale_statut('Mandat signe', ['mandat signe']),\n",
    "            'motif_revente': random.choice(MOTIFS_REVENTE),\n",
    "            'mandat_revente': random.choice(['SIMPLE','EXCLUSIF','Simple','Exclusif']),\n",
    "            'conseiller_revente_id': sale_null(random.choice(cons_ids)),\n",
    "            'nombre_visites': random.randint(0, 5),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 12 — src_expertise_comptable_lmnp\n",
    "# ============================================================\n",
    "\n",
    "def generer_lmnp(n, start_num):\n",
    "    rows = []\n",
    "    ventes_lmnp = spark.sql(\n",
    "        f\"\"\"SELECT v.vente_id, v.investisseur_id, v.lot_id, v.programme_id\n",
    "            FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres v\n",
    "            WHERE v.is_deleted = false\n",
    "            ORDER BY RAND() LIMIT {n * 3}\"\"\"\n",
    "    ).toPandas()\n",
    "\n",
    "    if len(ventes_lmnp) == 0:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    cpt_ids = [f\"CPT_{str(i).zfill(3)}\" for i in range(1, 20)]\n",
    "    regimes = ['LMNP micro-BIC','LMNP reel','LMNP reel','LMNP reel']\n",
    "    statuts = ['En cours','Declare','En attente documents']\n",
    "    annee_fiscale = DATE_J1.year - 1  # Déclaration de l'année précédente\n",
    "\n",
    "    sample = ventes_lmnp.sample(min(n, len(ventes_lmnp)))\n",
    "    for i, (_, v) in enumerate(sample.iterrows()):\n",
    "        lid = f\"LMNP_{str(start_num + i + 1).zfill(6)}\"\n",
    "        recettes = round(random.uniform(8000, 40000), 2)\n",
    "        charges = round(recettes * random.uniform(0.20, 0.45), 2)\n",
    "        amortissements = round(recettes * random.uniform(0.15, 0.60), 2)\n",
    "        resultat = round(recettes - charges - amortissements, 2)\n",
    "        impot = round(max(0, resultat * 0.30), 2)\n",
    "        rows.append({\n",
    "            'dossier_comptable_id': lid,\n",
    "            'investisseur_id': v['investisseur_id'],\n",
    "            'vente_id': v['vente_id'],\n",
    "            'lot_id': v['lot_id'],\n",
    "            'programme_id': sale_null(v['programme_id'], taux=0.1),\n",
    "            'annee_fiscale': annee_fiscale,\n",
    "            'regime_fiscal': random.choice(regimes),\n",
    "            'statut_dossier_comptable': random.choice(statuts),\n",
    "            'date_ouverture': DATE_J1_STR,\n",
    "            'date_reception_documents': sale_null(\n",
    "                (DATE_J1 + timedelta(days=random.randint(10, 45))).strftime('%Y-%m-%d'),\n",
    "                taux=0.3\n",
    "            ),\n",
    "            'date_declaration': sale_null(\n",
    "                (DATE_J1 + timedelta(days=random.randint(30, 90))).strftime('%Y-%m-%d'),\n",
    "                taux=0.5\n",
    "            ),\n",
    "            'recettes_locatives': recettes,\n",
    "            'charges_deductibles': charges,\n",
    "            'amortissements': amortissements,\n",
    "            'resultat_fiscal': resultat,\n",
    "            'impot_estime': impot,\n",
    "            'comptable_id': random.choice(cpt_ids),\n",
    "            'nombre_relances': random.randint(0, 5),\n",
    "            'pieces_manquantes': sale_null(random.choice([\n",
    "                'Relevés bancaires','Factures travaux','Quittances loyer',None\n",
    "            ])),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_deleted': False\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# GÉNÉRATEUR 13 — src_objectifs_commerciaux (1er du mois)\n",
    "# ============================================================\n",
    "\n",
    "def generer_objectifs(n, start_num):\n",
    "    rows = []\n",
    "    annee = DATE_J1.year\n",
    "    mois = DATE_J1.month\n",
    "    periode = f\"{annee}-{str(mois).zfill(2)}\"\n",
    "    familles = ['Immobilier direct','Pierre papier','Crowdfunding']\n",
    "    types = ['VEFA','SCPI','SCI','Crowdfunding immo']\n",
    "\n",
    "    for i in range(n):\n",
    "        oid = f\"OBJ_{str(start_num + i + 1).zfill(6)}\"\n",
    "        agence_id = choix_agence()\n",
    "        region_id = REF_AGENCES[\n",
    "            REF_AGENCES['agence_id'] == agence_id\n",
    "        ]['region_id'].values[0]\n",
    "        niveau = random.choices(\n",
    "            ['Conseiller','Agence','Region'],\n",
    "            weights=[0.50, 0.35, 0.15]\n",
    "        )[0]\n",
    "        conseiller_id = (\n",
    "            conseiller_pour_agence(agence_id) if niveau == 'Conseiller' else None\n",
    "        )\n",
    "        objectif_ca = random.randint(200000, 3000000)\n",
    "        rows.append({\n",
    "            'objectif_id': oid,\n",
    "            'annee': annee,\n",
    "            'mois': mois,\n",
    "            'periode': periode,\n",
    "            'niveau_objectif': niveau,\n",
    "            'region_id': region_id,\n",
    "            'agence_id': agence_id,\n",
    "            'conseiller_id': conseiller_id,\n",
    "            'partenaire_id': None,\n",
    "            'famille_produit': random.choice(familles),\n",
    "            'type_produit': random.choice(types),\n",
    "            'objectif_ca': objectif_ca,\n",
    "            'objectif_nombre_ventes': random.randint(1, 20),\n",
    "            'objectif_nombre_reservations': random.randint(5, 60),\n",
    "            'objectif_montant_souscriptions': random.randint(500000, 3000000),\n",
    "            'objectif_commissions': round(objectif_ca * random.uniform(0.03, 0.06), 2),\n",
    "            'objectif_nouveaux_clients': random.randint(10, 100),\n",
    "            'created_at': DATE_J1_STR,\n",
    "            'updated_at': DATE_J1_STR,\n",
    "            'is_active': True\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "print(\"Générateurs chargés ✓\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ▶ CELLULE 6 — EXÉCUTION & ÉCRITURE DELTA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# ORCHESTRATION PRINCIPALE\n",
    "# Récupère les max IDs, génère, écrit en APPEND\n",
    "# ============================================================\n",
    "\n",
    "def ecrire_delta(df_pandas, table_name):\n",
    "    \"\"\"Écrit un DataFrame pandas dans une table Delta en APPEND.\"\"\"\n",
    "    if df_pandas is None or len(df_pandas) == 0:\n",
    "        print(f\"  ⏭  {table_name} — 0 lignes, ignorée\")\n",
    "        return 0\n",
    "\n",
    "    df_spark = spark.createDataFrame(df_pandas)\n",
    "\n",
    "    if MODE_ECRITURE == 'dry_run':\n",
    "        print(f\"  🔍 [DRY RUN] {table_name} — {len(df_pandas)} lignes à écrire\")\n",
    "        df_spark.show(3, truncate=True)\n",
    "        return len(df_pandas)\n",
    "\n",
    "    write_mode = 'overwrite' if MODE_ECRITURE == 'overwrite' else 'append'\n",
    "    (\n",
    "        df_spark.write\n",
    "        .format('delta')\n",
    "        .mode(write_mode)\n",
    "        .saveAsTable(f\"{LAKEHOUSE_NAME}.{table_name}\")\n",
    "    )\n",
    "    print(f\"  ✅ {table_name} — {len(df_pandas)} lignes ajoutées\")\n",
    "    return len(df_pandas)\n",
    "\n",
    "\n",
    "# ── Récupération des derniers IDs ────────────────────────────\n",
    "print(\"Récupération des derniers IDs...\")\n",
    "\n",
    "last_prospect   = get_max_id('src_crm_prospects',             'prospect_id',             'PROSP_', 6)\n",
    "last_evt        = get_max_id('src_evenements_clients',        'evenement_id',            'EVT_',   7)\n",
    "last_res        = get_max_id('src_reservations_immobilieres', 'reservation_id',          'RES_',   6)\n",
    "last_vente      = get_max_id('src_ventes_immobilieres',       'vente_id',                'VTE_',   6)\n",
    "last_fin        = get_max_id('src_financements',              'financement_id',          'FIN_',   6)\n",
    "last_comm       = get_max_id('src_commissions',               'commission_id',           'COM_',   6)\n",
    "last_adv        = get_max_id('src_dossiers_adv',              'dossier_adv_id',          'ADV_',   6)\n",
    "last_sou        = get_max_id('src_souscriptions_pierre_papier','souscription_id',        'SOU_',   6)\n",
    "last_gl         = get_max_id('src_gestion_locative',          'gestion_id',              'GL_',    6)\n",
    "last_rec        = get_max_id('src_reclamations_incidents',    'reclamation_id',          'REC_',   6)\n",
    "last_rev        = get_max_id('src_revente_biens',             'revente_id',              'REV_',   6)\n",
    "last_lmnp       = get_max_id('src_expertise_comptable_lmnp',  'dossier_comptable_id',    'LMNP_',  6)\n",
    "last_obj        = get_max_id('src_objectifs_commerciaux',     'objectif_id',             'OBJ_',   6)\n",
    "\n",
    "print(\"IDs récupérés ✓\")\n",
    "\n",
    "# ── Génération ──────────────────────────────────────────────\n",
    "print(f\"\\n{'='*55}\")\n",
    "print(f\" GÉNÉRATION J-1 : {DATE_J1_STR}\")\n",
    "print(f\"{'='*55}\")\n",
    "\n",
    "total_lignes = 0\n",
    "\n",
    "# 1. Prospects\n",
    "n = nb_lignes(VOL_PROSPECTS)\n",
    "df = generer_prospects(n, last_prospect)\n",
    "total_lignes += ecrire_delta(df, 'src_crm_prospects')\n",
    "\n",
    "# 2. Événements clients\n",
    "n = nb_lignes(VOL_EVENEMENTS)\n",
    "df = generer_evenements(n, last_evt)\n",
    "total_lignes += ecrire_delta(df, 'src_evenements_clients')\n",
    "\n",
    "# 3. Réservations\n",
    "n = nb_lignes(VOL_RESERVATIONS)\n",
    "df_res = generer_reservations(n, last_res)\n",
    "total_lignes += ecrire_delta(df_res, 'src_reservations_immobilieres')\n",
    "\n",
    "# 4. Ventes (basées sur réservations existantes)\n",
    "n = nb_lignes(VOL_VENTES)\n",
    "df_ventes = generer_ventes(n, last_vente, df_res)\n",
    "total_lignes += ecrire_delta(df_ventes, 'src_ventes_immobilieres')\n",
    "\n",
    "# 5. Financements\n",
    "n = nb_lignes(VOL_FINANCEMENTS)\n",
    "df = generer_financements(n, last_fin)\n",
    "total_lignes += ecrire_delta(df, 'src_financements')\n",
    "\n",
    "# 6. Dossiers ADV\n",
    "n = nb_lignes(VOL_DOSSIERS_ADV)\n",
    "df = generer_dossiers_adv(n, last_adv)\n",
    "total_lignes += ecrire_delta(df, 'src_dossiers_adv')\n",
    "\n",
    "# 7. Commissions\n",
    "n = nb_lignes(VOL_COMMISSIONS)\n",
    "df = generer_commissions(n, last_comm)\n",
    "total_lignes += ecrire_delta(df, 'src_commissions')\n",
    "\n",
    "# 8. Souscriptions pierre papier\n",
    "n = nb_lignes(VOL_SOUSCRIPTIONS)\n",
    "df = generer_souscriptions(n, last_sou)\n",
    "total_lignes += ecrire_delta(df, 'src_souscriptions_pierre_papier')\n",
    "\n",
    "# 9. Gestion locative\n",
    "n = nb_lignes(VOL_GESTION_LOCATIVE)\n",
    "df = generer_gestion_locative(n, last_gl)\n",
    "total_lignes += ecrire_delta(df, 'src_gestion_locative')\n",
    "\n",
    "# 10. Réclamations\n",
    "n = nb_lignes(VOL_RECLAMATIONS)\n",
    "df = generer_reclamations(n, last_rec)\n",
    "total_lignes += ecrire_delta(df, 'src_reclamations_incidents')\n",
    "\n",
    "# 11. Reventas\n",
    "n = nb_lignes(VOL_REVENTAS)\n",
    "df = generer_reventas(n, last_rev)\n",
    "total_lignes += ecrire_delta(df, 'src_revente_biens')\n",
    "\n",
    "# 12. LMNP\n",
    "n = nb_lignes(VOL_LMNP)\n",
    "df = generer_lmnp(n, last_lmnp)\n",
    "total_lignes += ecrire_delta(df, 'src_expertise_comptable_lmnp')\n",
    "\n",
    "# 13. Objectifs — batch 1er du mois uniquement\n",
    "if IS_PREMIER_DU_MOIS:\n",
    "    n = random.randint(*VOL_OBJECTIFS_MENSUEL)\n",
    "    df = generer_objectifs(n, last_obj)\n",
    "    total_lignes += ecrire_delta(df, 'src_objectifs_commerciaux')\n",
    "else:\n",
    "    print(f\"  ⏭  src_objectifs_commerciaux — batch mensuel (pas le 1er du mois)\")\n",
    "\n",
    "# ── Résumé ──────────────────────────────────────────────────\n",
    "print(f\"\"\"\n",
    "╔══════════════════════════════════════════════════════╗\n",
    "║  SIMULATION J-1 TERMINÉE                            ║\n",
    "╠══════════════════════════════════════════════════════╣\n",
    "║  Date simulée  : {DATE_J1_STR}                        ║\n",
    "║  Lignes totales: {total_lignes:<5}                            ║\n",
    "║  Mode          : {MODE_ECRITURE:<10}                       ║\n",
    "║  Lakehouse     : {LAKEHOUSE_NAME:<20}         ║\n",
    "╚══════════════════════════════════════════════════════╝\"\"\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ▶ CELLULE 7 — CONTRÔLES QUALITÉ POST-GÉNÉRATION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Contrôles qualité rapides sur les données du jour\n",
    "# Pour alimenter un rapport de monitoring\n",
    "# ============================================================\n",
    "\n",
    "print(f\"\\n=== CONTRÔLES QUALITÉ — {DATE_J1_STR} ===\")\n",
    "\n",
    "checks = spark.sql(f\"\"\"\n",
    "    SELECT\n",
    "        '{DATE_J1_STR}'                                         AS date_run,\n",
    "        (SELECT COUNT(*) FROM {LAKEHOUSE_NAME}.src_crm_prospects\n",
    "         WHERE date_creation = '{DATE_J1_STR}')                 AS nouveaux_prospects,\n",
    "        (SELECT COUNT(*) FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres\n",
    "         WHERE date_signature_contrat = '{DATE_J1_STR}')        AS nouvelles_ventes,\n",
    "        (SELECT COUNT(*) FROM {LAKEHOUSE_NAME}.src_reservations_immobilieres\n",
    "         WHERE date_reservation = '{DATE_J1_STR}')              AS nouvelles_reservations,\n",
    "        (SELECT COUNT(*) FROM {LAKEHOUSE_NAME}.src_commissions\n",
    "         WHERE date_calcul = '{DATE_J1_STR}')                   AS nouvelles_commissions,\n",
    "        (SELECT COUNT(*) FROM {LAKEHOUSE_NAME}.src_reclamations_incidents\n",
    "         WHERE date_ouverture = '{DATE_J1_STR}')                AS nouvelles_reclamations,\n",
    "        (SELECT COUNT(*) FROM {LAKEHOUSE_NAME}.src_crm_prospects\n",
    "         WHERE date_creation = '{DATE_J1_STR}'\n",
    "         AND email IS NULL)                                      AS prospects_sans_email,\n",
    "        (SELECT COUNT(*) FROM {LAKEHOUSE_NAME}.src_ventes_immobilieres\n",
    "         WHERE date_signature_contrat = '{DATE_J1_STR}'\n",
    "         AND date_livraison_prevue < date_signature_acte)        AS dates_incoherentes_ventes\n",
    "\"\"\")\n",
    "\n",
    "checks.show(truncate=False)\n",
    "\n",
    "# Écriture du log de run dans une table de monitoring\n",
    "(\n",
    "    checks.write\n",
    "    .format('delta')\n",
    "    .mode('append')\n",
    "    .saveAsTable(f\"{LAKEHOUSE_NAME}.monitoring_simulation_log\")\n",
    ")\n",
    "\n",
    "print(\"Log de monitoring écrit ✓\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  },
  "trident": {
   "lakehouse": {
    "default_lakehouse": "LH_Immobilier_DEV",
    "known_lakehouses": [
     {"id": "LH_Immobilier_DEV"},
     {"id": "LH_Immobilier_PREPROD"},
     {"id": "LH_Immobilier_PROD"}
    ]
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
