CREATE TABLE [gold].[dim_programme_immobilier] (

	[programme_key] varchar(400) NULL, 
	[programme_id] varchar(50) NULL, 
	[nom_programme] varchar(8000) NULL, 
	[type_programme] varchar(8000) NULL, 
	[promoteur_id] varchar(50) NULL, 
	[ville] varchar(8000) NULL, 
	[code_postal] varchar(8000) NULL, 
	[region] varchar(8000) NULL, 
	[adresse] varchar(8000) NULL, 
	[latitude] decimal(10,6) NULL, 
	[longitude] decimal(10,6) NULL, 
	[type_actif] varchar(8000) NULL, 
	[segment_marche] varchar(8000) NULL, 
	[statut_programme] varchar(8000) NULL, 
	[date_lancement_commercial] date NULL, 
	[date_livraison_prevue] date NULL, 
	[date_livraison_reelle] date NULL, 
	[nombre_lots_total] int NULL, 
	[nombre_lots_disponibles] int NULL, 
	[prix_moyen_m2] decimal(18,2) NULL, 
	[rentabilite_cible] decimal(9,4) NULL, 
	[zone_fiscale] varchar(8000) NULL, 
	[dispositif_fiscal] varchar(8000) NULL, 
	[label_energetique] varchar(8000) NULL, 
	[note_programme] decimal(5,2) NULL, 
	[is_active] bit NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL
);