CREATE TABLE [gold].[fact_revente] (

	[revente_key] varchar(400) NULL, 
	[revente_id] varchar(50) NULL, 
	[vente_id] varchar(50) NULL, 
	[date_demande_revente_key] int NULL, 
	[date_mise_en_marche_key] int NULL, 
	[date_revente_key] int NULL, 
	[investisseur_key] varchar(400) NULL, 
	[programme_key] varchar(400) NULL, 
	[lot_key] varchar(400) NULL, 
	[statut_key] varchar(400) NULL, 
	[investisseur_id] varchar(50) NULL, 
	[programme_id] varchar(50) NULL, 
	[lot_id] varchar(50) NULL, 
	[conseiller_revente_id] varchar(50) NULL, 
	[prix_achat_initial] decimal(18,2) NULL, 
	[prix_revente_estime] decimal(18,2) NULL, 
	[prix_revente_final] decimal(18,2) NULL, 
	[plus_value_brute] decimal(18,2) NULL, 
	[plus_value_nette] decimal(18,2) NULL, 
	[nombre_visites] int NULL, 
	[statut_revente] varchar(8000) NULL, 
	[motif_revente] varchar(8000) NULL, 
	[mandat_revente] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL
);