CREATE TABLE [gold].[fact_reservation] (

	[reservation_key] varchar(400) NULL, 
	[reservation_id] varchar(50) NULL, 
	[date_reservation_key] int NULL, 
	[date_annulation_key] int NULL, 
	[date_expiration_reservation_key] int NULL, 
	[investisseur_key] varchar(400) NULL, 
	[partenaire_key] varchar(400) NULL, 
	[conseiller_key] varchar(400) NULL, 
	[agence_region_key] varchar(400) NULL, 
	[programme_key] varchar(400) NULL, 
	[lot_key] varchar(400) NULL, 
	[statut_key] varchar(400) NULL, 
	[lot_id] varchar(50) NULL, 
	[programme_id] varchar(50) NULL, 
	[investisseur_id] varchar(50) NULL, 
	[partenaire_id] varchar(50) NULL, 
	[conseiller_id] varchar(50) NULL, 
	[agence_id] varchar(50) NULL, 
	[montant_reservation] decimal(18,2) NULL, 
	[prix_reserve] decimal(18,2) NULL, 
	[remise_appliquee] decimal(18,2) NULL, 
	[apport_prevu] decimal(18,2) NULL, 
	[montant_credit_prevu] decimal(18,2) NULL, 
	[canal_reservation] varchar(8000) NULL, 
	[mode_financement_prevu] varchar(8000) NULL, 
	[statut_reservation] varchar(8000) NULL, 
	[motif_annulation] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL
);