CREATE TABLE [gold].[fact_operation_crowdfunding] (

	[crowdfunding_key] varchar(400) NULL, 
	[operation_crowdfunding_id] varchar(50) NULL, 
	[projet_id] varchar(50) NULL, 
	[date_investissement_key] int NULL, 
	[date_remboursement_prevue_key] int NULL, 
	[date_remboursement_reelle_key] int NULL, 
	[investisseur_key] varchar(400) NULL, 
	[partenaire_key] varchar(400) NULL, 
	[conseiller_key] varchar(400) NULL, 
	[agence_region_key] varchar(400) NULL, 
	[statut_key] varchar(400) NULL, 
	[investisseur_id] varchar(50) NULL, 
	[partenaire_id] varchar(50) NULL, 
	[conseiller_id] varchar(50) NULL, 
	[agence_id] varchar(50) NULL, 
	[promoteur_id] varchar(50) NULL, 
	[nom_projet] varchar(8000) NULL, 
	[ville] varchar(8000) NULL, 
	[region] varchar(8000) NULL, 
	[montant_investi] decimal(18,2) NULL, 
	[taux_rendement_annuel_prevu] decimal(9,4) NULL, 
	[duree_mois] int NULL, 
	[montant_rembourse] decimal(18,2) NULL, 
	[interets_bruts] decimal(18,2) NULL, 
	[fiscalite_appliquee] varchar(8000) NULL, 
	[incident_paiement] bit NULL, 
	[statut_operation] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL
);