CREATE TABLE [gold].[fact_vente] (

	[vente_key] varchar(400) NULL, 
	[vente_id] varchar(50) NULL, 
	[reservation_id] varchar(50) NULL, 
	[date_signature_contrat_key] int NULL, 
	[date_signature_acte_key] int NULL, 
	[date_livraison_prevue_key] int NULL, 
	[date_livraison_reelle_key] int NULL, 
	[investisseur_key] varchar(400) NULL, 
	[partenaire_key] varchar(400) NULL, 
	[conseiller_key] varchar(400) NULL, 
	[agence_region_key] varchar(400) NULL, 
	[programme_key] varchar(400) NULL, 
	[lot_key] varchar(400) NULL, 
	[statut_key] varchar(400) NULL, 
	[lot_id] varchar(50) NULL, 
	[programme_id] varchar(50) NULL, 
	[investisseur_id] varchar(50) NULL, 
	[partenaire_id] varchar(50) NULL, 
	[conseiller_id] varchar(50) NULL, 
	[agence_id] varchar(50) NULL, 
	[prix_vente_ht] decimal(18,2) NULL, 
	[prix_vente_ttc] decimal(18,2) NULL, 
	[tva] decimal(18,2) NULL, 
	[frais_notaire] decimal(18,2) NULL, 
	[montant_total_operation] decimal(18,2) NULL, 
	[montant_apport] decimal(18,2) NULL, 
	[montant_credit] decimal(18,2) NULL, 
	[mode_financement] varchar(8000) NULL, 
	[banque_financement] varchar(8000) NULL, 
	[statut_vente] varchar(8000) NULL, 
	[motif_echec] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL
);