CREATE TABLE [gold].[fact_souscription_pierre_papier] (

	[souscription_key] varchar(400) NULL, 
	[souscription_id] varchar(50) NULL, 
	[date_souscription_key] int NULL, 
	[date_validation_key] int NULL, 
	[date_rejet_key] int NULL, 
	[investisseur_key] varchar(400) NULL, 
	[partenaire_key] varchar(400) NULL, 
	[conseiller_key] varchar(400) NULL, 
	[agence_region_key] varchar(400) NULL, 
	[produit_key] varchar(400) NULL, 
	[statut_key] varchar(400) NULL, 
	[investisseur_id] varchar(50) NULL, 
	[partenaire_id] varchar(50) NULL, 
	[conseiller_id] varchar(50) NULL, 
	[agence_id] varchar(50) NULL, 
	[produit_id] varchar(50) NULL, 
	[societe_gestion_id] varchar(50) NULL, 
	[type_support] varchar(8000) NULL, 
	[nom_support] varchar(8000) NULL, 
	[montant_souscrit] decimal(18,2) NULL, 
	[nombre_parts] decimal(18,4) NULL, 
	[prix_part] decimal(18,2) NULL, 
	[frais_souscription] decimal(18,2) NULL, 
	[rendement_previsionnel] decimal(9,4) NULL, 
	[duree_recommandee] varchar(8000) NULL, 
	[statut_souscription] varchar(8000) NULL, 
	[motif_rejet] varchar(8000) NULL, 
	[mode_paiement] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL
);