CREATE TABLE [gold].[fact_dossier_adv] (

	[dossier_adv_key] varchar(400) NULL, 
	[dossier_adv_id] varchar(50) NULL, 
	[vente_id] varchar(50) NULL, 
	[reservation_id] varchar(50) NULL, 
	[date_ouverture_dossier_key] int NULL, 
	[date_reception_pieces_key] int NULL, 
	[date_validation_dossier_key] int NULL, 
	[date_envoi_notaire_key] int NULL, 
	[date_signature_acte_key] int NULL, 
	[investisseur_key] varchar(400) NULL, 
	[partenaire_key] varchar(400) NULL, 
	[conseiller_key] varchar(400) NULL, 
	[programme_key] varchar(400) NULL, 
	[lot_key] varchar(400) NULL, 
	[statut_key] varchar(400) NULL, 
	[investisseur_id] varchar(50) NULL, 
	[partenaire_id] varchar(50) NULL, 
	[conseiller_id] varchar(50) NULL, 
	[programme_id] varchar(50) NULL, 
	[lot_id] varchar(50) NULL, 
	[responsable_adv_id] varchar(50) NULL, 
	[statut_dossier] varchar(8000) NULL, 
	[delai_traitement_jours] int NULL, 
	[pieces_manquantes] bit NULL, 
	[nombre_relances] int NULL, 
	[blocage_adv] bit NULL, 
	[motif_blocage] varchar(8000) NULL, 
	[commentaire_adv] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL
);